### ISSUE TITLE
IllegalAccessError with java 17

### ISSUE THREAD

**Issue by Gamebuster19901** [WilderForge/WilderForge#44]
```
0:34:962 5 LegacyDesktop exiting due to fatal runtime error com.badlogic.gdx.utils.GdxRuntimeException: java.lang.IllegalAccessError: class com.worldwalkergames.legacy.server.context.ServerDataContext$ModAwareResourceBundle (in unnamed module @0x248d4f4a) cannot access class sun.util.ResourceBundleEnumeration (in module java.base) because module java.base does not export sun.util to unnamed module @0x248d4f4a
	at com.badlogic.gdx.backends.lwjgl3.NiceLwjgl3Application.<init>(NiceLwjgl3Application.java:86)
	at com.worldwalkergames.legacy.LegacyDesktop.main(LegacyDesktop.java:125)
Caused by: java.lang.IllegalAccessError: class com.worldwalkergames.legacy.server.context.ServerDataContext$ModAwareResourceBundle (in unnamed module @0x248d4f4a) cannot access class sun.util.ResourceBundleEnumeration (in module java.base) because module java.base does not export sun.util to unnamed module @0x248d4f4a
	at com.worldwalkergames.legacy.server.context.ServerDataContext$ModAwareResourceBundle.getKeys(ServerDataContext.java:989)
	at java.base/java.util.ResourceBundle.handleKeySet(ResourceBundle.java:2342)
	at java.base/java.util.ResourceBundle.containsKey(ResourceBundle.java:2297)
	at com.worldwalkergames.legacy.localization.StringLookup.getFromBundle(StringLookup.java:140)
	at com.worldwalkergames.legacy.localization.StringLookup.get(StringLookup.java:91)
	at com.worldwalkergames.legacy.context.GameStrings.getWithTemplateFallback(GameStrings.java:367)
	at com.worldwalkergames.legacy.context.GameStrings.aspectName(GameStrings.java:226)
	at com.worldwalkergames.legacy.context.GameStrings.getAspectChangedText(GameStrings.java:3857)
	at com.worldwalkergames.legacy.game.mission.MissionAnimation.animateAspectChanged(MissionAnimation.java:472)
	at com.worldwalkergames.legacy.game.common.ClientStateChangeHandler$ClientAspectChanged.handle(ClientStateChangeHandler.java:532)
	at com.worldwalkergames.legacy.game.common.ClientStateChangeHandler$ClientAspectChanged.handle(ClientStateChangeHandler.java:521)
	at com.worldwalkergames.legacy.game.common.ClientStateChangeHandler.processChangeContext(ClientStateChangeHandler.java:322)
	at com.worldwalkergames.legacy.game.common.ClientStateChangeHandler.processChangeContext(ClientStateChangeHandler.java:314)
	at com.worldwalkergames.legacy.game.common.ClientStateChangeHandler.update(ClientStateChangeHandler.java:170)
	at com.worldwalkergames.legacy.game.mission.systems.StateChangeAnimator.update(StateChangeAnimator.java:30)
	at com.worldwalkergames.engine.DrivableContainer.update(DrivableContainer.java:39)
	at com.worldwalkergames.engine.Domain.update(Domain.java:81)
	at com.worldwalkergames.legacy.game.mission.ClientMissionDomain.update(ClientMissionDomain.java:126)
	at com.worldwalkergames.legacy.game.mission.ui.MissionScreen$1.update(MissionScreen.java:124)
	at com.worldwalkergames.engine.DrivableContainer.update(DrivableContainer.java:39)
	at com.worldwalkergames.legacy.game.mission.ui.MissionScreen.update(MissionScreen.java:161)
	at com.worldwalkergames.engine.DrivableContainer.update(DrivableContainer.java:39)
	at com.worldwalkergames.legacy.ui.LegacyUIRoot.update(LegacyUIRoot.java:545)
	at com.worldwalkergames.legacy.ui.MainScreen.update(MainScreen.java:197)
	at com.worldwalkergames.legacy.LegacyDesktop.render(LegacyDesktop.java:318)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:403)
	at com.badlogic.gdx.backends.lwjgl3.NiceLwjgl3Application.loop(NiceLwjgl3Application.java:104)
	at com.badlogic.gdx.backends.lwjgl3.NiceLwjgl3Application.<init>(NiceLwjgl3Application.java:80)
	... 1 more

```

**Comment by Gamebuster19901** [comment]
This was also fixed officially, however this backports the fix to all versions.

**Comment by Gamebuster19901** [comment]
```
Wildermyth has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NullPointerException
	at com.wildermods.provider.services.WildermythGameProvider.launch(WildermythGameProvider.java:305)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at com.wildermods.wilderloader.Main.main(Main.java:70)
Caused by: java.lang.NullPointerException
	at com.worldwalkergames.legacy.server.context.ServerDataContext$ModAwareResourceBundle.handler$zbi000$fixIllegalAccessError(ServerDataContext.java:1573)
	at com.worldwalkergames.legacy.server.context.ServerDataContext$ModAwareResourceBundle.getKeys(ServerDataContext.java)
	at java.base/java.util.ResourceBundle.handleKeySet(ResourceBundle.java:2350)
	at java.base/java.util.ResourceBundle.containsKey(ResourceBundle.java:2305)
	at com.worldwalkergames.legacy.localization.StringLookup.getFromBundle(StringLookup.java:140)
	at com.worldwalkergames.legacy.localization.StringLookup.get(StringLookup.java:91)
	at com.worldwalkergames.legacy.context.GameStrings.getWithTemplateFallback(GameStrings.java:367)
	at com.worldwalkergames.legacy.context.GameStrings.aspectName(GameStrings.java:226)
	at com.worldwalkergames.legacy.ui.detail.AbilitiesDetails.buildProgress(AbilitiesDetails.java:93)
	at com.worldwalkergames.legacy.ui.detail.AbilitiesDetails.buildPanels(AbilitiesDetails.java:80)
	at com.worldwalkergames.legacy.ui.detail.DetailsPanel.rebuild(DetailsPanel.java:145)
	at com.worldwalkergames.legacy.ui.detail.DetailsPanel.setTarget(DetailsPanel.java:112)
	at com.worldwalkergames.legacy.ui.detail.CharacterSheetPopup.selectTab(CharacterSheetPopup.java:989)
	at com.worldwalkergames.legacy.ui.detail.CharacterSheetPopup.build(CharacterSheetPopup.java:764)
	at com.worldwalkergames.legacy.ui.detail.CharacterSheetPopup.update(CharacterSheetPopup.java:943)
	at com.worldwalkergames.ui.popup.PopUpManager.update(PopUpManager.java:232)
	at com.worldwalkergames.legacy.ui.LegacyUIRoot.update(LegacyUIRoot.java:546)
	at com.worldwalkergames.legacy.ui.MainScreen.update(MainScreen.java:197)
	at com.worldwalkergames.legacy.LegacyDesktop.render(LegacyDesktop.java:318)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:403)
	at com.badlogic.gdx.backends.lwjgl3.NiceLwjgl3Application.loop(NiceLwjgl3Application.java:104)
	at com.badlogic.gdx.backends.lwjgl3.NiceLwjgl3Application.<init>(NiceLwjgl3Application.java:80)
	at com.worldwalkergames.legacy.LegacyDesktop.main(LegacyDesktop.java:125)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.wildermods.provider.services.WildermythGameProvider.launch(WildermythGameProvider.java:302)
	... 3 more

```

**Comment by Gamebuster19901** [comment]
This isn't actually fixed in vanilla version 1.6+401

**Comment by Gamebuster19901** [comment]
This issue has been open for about three years, and the developers have been informed about it. Additionally, a fix has been provided to them.

Since this is still an issue in the main game, I'm going to assume this is a Won't Fix.

WilderForge will continue to modify the game to support the latest versions of java. See https://github.com/WilderForge/WilderForge/blob/master/src/main/java/com/wildermods/wilderforge/mixins/vanillafixes/ServerDataContextVanillaFixMixin.java

**Comment by Gamebuster19901** [comment]
Confirmed Won't Fix by the Developers.

![Image](https://github.com/user-attachments/assets/f3a1e007-2f18-4c50-94df-80597d9224bd)
