### ISSUE TITLE
Unable to launch after updating to fabric 0.16.0

### ISSUE THREAD

**Issue by Gamebuster19901** [WilderForge/WilderForge#51]
```
[00:54:38.569] Logging initialized.
[00:54:38.570] found fabric dependency file:/home/gamebuster/Desktop/wildermyth/wilderforge/bin/./fabric/error_prone_annotations-2.27.0.jar
[00:54:38.572] found fabric dependency file:/home/gamebuster/Desktop/wildermyth/wilderforge/bin/./fabric/failureaccess-1.0.2.jar
[00:54:38.574] found fabric dependency file:/home/gamebuster/Desktop/wildermyth/wilderforge/bin/./fabric/asm-util-9.7.jar
[00:54:38.575] found fabric dependency file:/home/gamebuster/Desktop/wildermyth/wilderforge/bin/./fabric/commons-lang3-3.14.0.jar
[00:54:38.576] found fabric dependency file:/home/gamebuster/Desktop/wildermyth/wilderforge/bin/./fabric/jsr305-3.0.2.jar
[00:54:38.577] found fabric dependency file:/home/gamebuster/Desktop/wildermyth/wilderforge/bin/./fabric/commons-text-1.12.0.jar
[00:54:38.577] found fabric dependency file:/home/gamebuster/Desktop/wildermyth/wilderforge/bin/./fabric/mixin-0.8.7.jar
[00:54:38.578] found fabric dependency file:/home/gamebuster/Desktop/wildermyth/wilderforge/bin/./fabric/access-widener-2.1.0.jar
[00:54:38.578] found fabric dependency file:/home/gamebuster/Desktop/wildermyth/wilderforge/bin/./fabric/asm-9.7.jar
[00:54:38.579] found fabric dependency file:/home/gamebuster/Desktop/wildermyth/wilderforge/bin/./fabric/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
[00:54:38.580] found fabric dependency file:/home/gamebuster/Desktop/wildermyth/wilderforge/bin/./fabric/asm-tree-9.7.jar
[00:54:38.580] found fabric dependency file:/home/gamebuster/Desktop/wildermyth/wilderforge/bin/./fabric/checker-qual-3.42.0.jar
[00:54:38.581] found fabric dependency file:/home/gamebuster/Desktop/wildermyth/wilderforge/bin/./fabric/gson-2.11.0.jar
[00:54:38.582] found fabric dependency file:/home/gamebuster/Desktop/wildermyth/wilderforge/bin/./fabric/asm-commons-9.7.jar
[00:54:38.582] found fabric dependency file:/home/gamebuster/Desktop/wildermyth/wilderforge/bin/./fabric/asm-analysis-9.7.jar
[00:54:38.583] found fabric dependency file:/home/gamebuster/Desktop/wildermyth/wilderforge/bin/./fabric/tiny-mappings-parser-0.3.0+build.17.jar
[00:54:38.584] found fabric dependency file:/home/gamebuster/Desktop/wildermyth/wilderforge/bin/./fabric/provider-1.3.1.0.jar
[00:54:38.584] found fabric dependency file:/home/gamebuster/Desktop/wildermyth/wilderforge/bin/./fabric/guava-33.2.1-jre.jar
[00:54:38.686] [main/ERROR] [Fabric Loader/] ASOFJIOAEWSIOUFHIUO
[00:54:38.700] Launch directory is /home/gamebuster/Desktop/wildermyth/wilderforge/bin
[00:54:38.701] Skipping non-jar dependency /home/gamebuster/Desktop/wildermyth/wilderforge/bin/./lib/natives
[00:54:38.702] Skipping wildermyth.jar
[00:54:38.702] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/mods
[00:54:38.702] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/fabric
[00:54:38.703] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/change log_de.txt
[00:54:38.703] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/readme.txt
[00:54:38.704] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/version.txt
[00:54:38.704] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/decomp
[00:54:38.705] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/change log_pt.txt
[00:54:38.705] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/config.json
[00:54:38.706] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/assets
[00:54:38.706] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/.fabric
[00:54:38.707] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/patchline.txt
[00:54:38.707] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/fabricloader.log
[00:54:38.708] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/wildermyth
[00:54:38.708] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/logs
[00:54:38.709] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/change log_ru.txt
[00:54:38.709] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/jre
[00:54:38.710] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/change log.txt
[00:54:38.710] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/main
[00:54:38.711] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/players
[00:54:38.711] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/change log_es.txt
[00:54:38.712] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/change log_fr.txt
[00:54:38.712] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/steam_appid.txt
[00:54:38.713] Skipping fabric dep fabric-loader-0.16.0.jar
[00:54:38.713] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/change log_zh_CN.txt
[00:54:38.713] Skipping non-jar file /home/gamebuster/Desktop/wildermyth/wilderforge/bin/lib
[00:54:38.716] [main/INFO] [Fabric Loader/GameProvider] Loading Wildermyth 1.16+543 with Fabric Loader 0.16.0
[00:54:38.739] entrypoint is com.worldwalkergames.legacy.LegacyDesktop
[00:54:38.744] Main method is <clinit>()V
[00:54:38.776] [ForkJoinPool-1-worker-2/WARN] [Fabric Loader/Metadata] The mod "wilderforge" contains invalid entries in its mod json:
[00:54:38.776] - Unsupported root entry "credits" at line 18 column 11
[00:54:38.777] [ForkJoinPool-1-worker-2/WARN] [Fabric Loader/Metadata] Mod wilderforge uses the version ${WILDERFORGE_VERSION} which isn't compatible with Loader's extended semantic version format (Could not parse version number component '${WILDERFORGE_VERSION}'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[00:54:38.810] [main/INFO] [Fabric Loader/] Loading 7 mods:
[00:54:38.811] 	- asm 9.0
[00:54:38.811] 	- fabricloader 0.16.0
[00:54:38.811] 	   \-- mixinextras 0.4.0
[00:54:38.811] 	- java 17
[00:54:38.811] 	- mixin 0.8.7
[00:54:38.811] 	- wilderforge ${WILDERFORGE_VERSION}
[00:54:38.812] 	- wildermyth 1.16+543
[00:54:38.857] [main/INFO] [Fabric Loader/Mixin] SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/home/gamebuster/.gradle/caches/modules-2/files-2.1/org.spongepowered/mixin/0.8.7/8ab114ac385e6dbdad5efafe28aba4df8120915f/mixin-0.8.7.jar Service=Knot/Fabric Env=CLIENT
[00:54:38.864] /*********************************************************************************************************************************************************************************************************/
[00:54:38.865] /*                                                                            SpongePowered MIXIN (Verbose debugging enabled)                                                                            */
[00:54:38.866] /*********************************************************************************************************************************************************************************************************/
[00:54:38.867] /*                                         Code source : file:/home/gamebuster/.gradle/caches/modules-2/files-2.1/org.spongepowered/mixin/0.8.7/8ab114ac385e6dbdad5efafe28aba4df8120915f/mixin-0.8.7.jar */
[00:54:38.868] /*                                    Internal Version : 0.8.7                                                                                                                                           */
[00:54:38.869] /*                                        Java Version : 17.0 (supports compatibility 6-17)                                                                                                              */
[00:54:38.870] /*                         Default Compatibility Level : JAVA_8                                                                                                                                          */
[00:54:38.871] /*                   Max Effective Compatibility Level : JAVA_13                                                                                                                                         */
[00:54:38.873] /*                                Detected ASM Version : ASM 9.7 (ASM10_EXPERIMENTAL)                                                                                                                    */
[00:54:38.874] /*                          Detected ASM Supports Java : Up to Java 23 (class file version 67.0)                                                                                                         */
[00:54:38.875] /*********************************************************************************************************************************************************************************************************/
[00:54:38.876] /*                                        Service Name : Knot/Fabric                                                                                                                                     */
[00:54:38.877] /*                                 Mixin Service Class : net.fabricmc.loader.impl.launch.knot.MixinServiceKnot                                                                                           */
[00:54:38.878] /*                       Global Property Service Class : net.fabricmc.loader.impl.launch.knot.FabricGlobalPropertyService                                                                                */
[00:54:38.879] /*                                 Logger Adapter Type : Fabric Mixin Logger                                                                                                                             */
[00:54:38.879] /*********************************************************************************************************************************************************************************************************/
[00:54:38.880] /*                                         mixin.debug : <true>                                                                                                                                          */
[00:54:38.881] /*                                  mixin.debug.export : - <true>                                                                                                                                        */
[00:54:38.882] /*                           mixin.debug.export.filter : - - <null>                                                                                                                                      */
[00:54:38.883] /*                        mixin.debug.export.decompile : - - <true>                                                                                                                                      */
[00:54:38.884] /*                  mixin.debug.export.decompile.async : - - - <true>                                                                                                                                    */
[00:54:38.885] /* mixin.debug.export.decompile.mergeGenericSignatures : - - - <true>                                                                                                                                    */
[00:54:38.886] /*                                  mixin.debug.verify : - <true>                                                                                                                                        */
[00:54:38.887] /*                                 mixin.debug.verbose : - <true>                                                                                                                                        */
[00:54:38.888] /*                         mixin.debug.countInjections : - <true>                                                                                                                                        */
[00:54:38.889] /*                                  mixin.debug.strict : - <false>                                                                                                                                       */
[00:54:38.890] /*                           mixin.debug.strict.unique : - - <false>                                                                                                                                     */
[00:54:38.891] /*                          mixin.debug.strict.targets : - - <false>                                                                                                                                     */
[00:54:38.891] /*                                mixin.debug.profiler : - <true>                                                                                                                                        */
[00:54:38.892] /*                           mixin.dumpTargetOnFailure : <true>                                                                                                                                          */
[00:54:38.893] /*                                        mixin.checks : <false>                                                                                                                                         */
[00:54:38.894] /*                             mixin.checks.interfaces : - <false>                                                                                                                                       */
[00:54:38.895] /*                      mixin.checks.interfaces.strict : - - <false>                                                                                                                                     */
[00:54:38.896] /*                             mixin.ignoreConstraints : <false>                                                                                                                                         */
[00:54:38.897] /*                                       mixin.hotSwap : <false>                                                                                                                                         */
[00:54:38.898] /*                                       mixin.env.obf : - <false>                                                                                                                                       */
[00:54:38.899] /*                             mixin.env.disableRefMap : - <false>                                                                                                                                       */
[00:54:38.900] /*                               mixin.env.remapRefMap : - <false>                                                                                                                                       */
[00:54:38.901] /*                       mixin.env.refMapRemappingFile : - <>                                                                                                                                            */
[00:54:38.901] /*                        mixin.env.refMapRemappingEnv : - <searge>                                                                                                                                      */
[00:54:38.902] /*                      mixin.env.allowPermissiveMatch : - <false>                                                                                                                                       */
[00:54:38.903] /*                            mixin.env.ignoreRequired : - <false>                                                                                                                                       */
[00:54:38.904] /*                               mixin.env.compatLevel : - <false>                                                                                                                                       */
[00:54:38.905] /*                          mixin.env.shiftByViolation : - <warn>                                                                                                                                        */
[00:54:38.906] /*                      mixin.initialiserInjectionMode : <default>                                                                                                                                       */
[00:54:38.907] /*               mixin.tunable.classReaderExpandFrames : - <false>                                                                                                                                       */
[00:54:38.908] /*********************************************************************************************************************************************************************************************************/
[00:54:38.909] /*                                    UNSAFE_INJECTION : available=<true> enabled=<true>                                                                                                                 */
[00:54:38.910] /*                       INJECTORS_IN_INTERFACE_MIXINS : available=<true> enabled=<true>                                                                                                                 */
[00:54:38.911] /*********************************************************************************************************************************************************************************************************/
[00:54:38.912] /*                                       Detected Side : CLIENT                                                                                                                                          */
[00:54:38.913] /*********************************************************************************************************************************************************************************************************/
[00:54:38.922] [main/INFO] [Fabric Loader/Mixin] Attempting to load Fernflower decompiler (Threaded mode)
[00:54:38.923] [main/INFO] [Fabric Loader/Mixin] Fernflower could not be loaded, exported classes will not be decompiled. NoClassDefFoundError: org/jetbrains/java/decompiler/main/extern/IResultSaver
[00:54:38.957] [main/ERROR] [Fabric Loader/] Catching java.lang.RuntimeException: Error creating Mixin config mixinextras.init.mixins.json for mod mixinextras
[00:54:38.957] 	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:96)
[00:54:38.958] 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
[00:54:38.958] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
[00:54:38.958] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[00:54:38.959] 	at com.wildermods.wilderloader.Main.main(Main.java:77)
[00:54:38.959] Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config mixinextras.init.mixins.json
[00:54:38.960] 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:168)
[00:54:38.960] 	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:121)
[00:54:38.960] 	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:98)
[00:54:38.961] 	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:94)
[00:54:38.961] 	... 4 more
[00:54:38.961] Caused by: java.lang.IllegalArgumentException: The specified resource 'mixinextras.init.mixins.json' was invalid or could not be read
[00:54:38.962] 	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1398)
[00:54:38.962] 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:163)
[00:54:38.962] 	... 7 more
[00:54:38.962] Caused by: java.lang.NullPointerException: Cannot invoke "org.spongepowered.asm.mixin.MixinEnvironment.getOption(org.spongepowered.asm.mixin.MixinEnvironment$Option)" because "this.env" is null
[00:54:38.963] 	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:466)
[00:54:38.964] 	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1391)
[00:54:38.964] 	... 8 more
[00:54:38.964] 
[00:54:38.964] java.lang.RuntimeException: Error creating Mixin config mixinextras.init.mixins.json for mod mixinextras
[00:54:38.965] 	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:96)
[00:54:38.965] 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
[00:54:38.965] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
[00:54:38.966] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[00:54:38.966] 	at com.wildermods.wilderloader.Main.main(Main.java:77)
[00:54:38.966] 	Suppressed: java.lang.Error: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "this.crashLogService" is null
[00:54:38.967] 		at com.wildermods.provider.services.WildermythGameProvider.displayCrash(WildermythGameProvider.java:335)
[00:54:38.967] 		at net.fabricmc.loader.impl.launch.FabricLauncherBase$1.uncaughtException(FabricLauncherBase.java:109)
[00:54:38.968] 		at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1082)
[00:54:38.968] 		at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1077)
[00:54:38.969] 		at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:2017)
[00:54:38.969] 	Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "this.crashLogService" is null
[00:54:38.969] 		at com.wildermods.provider.services.WildermythGameProvider.displayCrash(WildermythGameProvider.java:331)
[00:54:38.970] 		... 4 more
[00:54:38.970] Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config mixinextras.init.mixins.json
[00:54:38.971] 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:168)
[00:54:38.971] 	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:121)
[00:54:38.971] 	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:98)
[00:54:38.972] 	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:94)
[00:54:38.972] 	... 4 more
[00:54:38.972] Caused by: java.lang.IllegalArgumentException: The specified resource 'mixinextras.init.mixins.json' was invalid or could not be read
[00:54:38.973] 	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1398)
[00:54:38.973] 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:163)
[00:54:38.973] 	... 7 more
[00:54:38.973] Caused by: java.lang.NullPointerException: Cannot invoke "org.spongepowered.asm.mixin.MixinEnvironment.getOption(org.spongepowered.asm.mixin.MixinEnvironment$Option)" because "this.env" is null
[00:54:38.974] 	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:466)
[00:54:38.975] 	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1391)
[00:54:38.975] 	... 8 more
```

**Comment by Gamebuster19901** [comment]
Appears to be a conflict with fabric loader and the official sponepowered mixin

**Comment by Gamebuster19901** [comment]
Seems like it's not actually a conflict. It appears fabric's fork of mixin fixes an issue in mixin, but that fix was never propagated upstream to the official mixin repository.

**Comment by Gamebuster19901** [comment]
This was fixed by using fabric's fork of mixin in the game provider.
