### ISSUE TITLE
Game crash when opening credits via Credits Lab

### ISSUE THREAD

**Issue by Gamebuster19901** [WilderForge/WilderForge#52]
```
[06:45:38] [ERROR] [FabricLoader/]: Wildermyth has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NullPointerException: Cannot read field "perilAndOdesEnabled" because "com.worldwalkergames.legacy.game.campaign.model.GameSettings.in(com.worldwalkergames.engine.EntitiesCollection).scenarioInfo" is null
	at com.wildermods.provider.services.WildermythGameProvider.launch(WildermythGameProvider.java:366)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException: Cannot read field "perilAndOdesEnabled" because "com.worldwalkergames.legacy.game.campaign.model.GameSettings.in(com.worldwalkergames.engine.EntitiesCollection).scenarioInfo" is null
	at com.worldwalkergames.legacy.game.campaign.model.GameSettings.getPerilAndOdesEnabled(GameSettings.java:214)
	at com.worldwalkergames.legacy.ui.credits.GameResultsDisplay.buildSummary(GameResultsDisplay.java:569)
	at com.worldwalkergames.legacy.ui.credits.GameResultsDisplay.build(GameResultsDisplay.java:437)
	at com.worldwalkergames.legacy.ui.credits.GameResultsDisplay.before(GameResultsDisplay.java:372)
	at com.worldwalkergames.engine.DrivableContainer.driveChild(DrivableContainer.java:79)
	at com.worldwalkergames.scratchpad.CreditsLab.update(CreditsLab.java:210)
	at com.worldwalkergames.ViewStackManager.update(ViewStackManager.java:99)
	at com.worldwalkergames.scratchpad.ui.ScreenManager.update(ScreenManager.java:41)
	at com.worldwalkergames.engine.DrivableContainer.update(DrivableContainer.java:39)
	at com.worldwalkergames.scratchpad.EmbeddedScratchpadScreen.update(EmbeddedScratchpadScreen.java:143)
	at com.worldwalkergames.engine.DrivableContainer.update(DrivableContainer.java:39)
	at com.worldwalkergames.legacy.ui.LegacyUIRoot.update(LegacyUIRoot.java:662)
	at com.worldwalkergames.legacy.ui.MainScreen.update(MainScreen.java:214)
	at com.worldwalkergames.legacy.LegacyDesktop.render(LegacyDesktop.java:344)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
	at com.badlogic.gdx.backends.lwjgl3.NiceLwjgl3Application.loop(NiceLwjgl3Application.java:104)
	at com.badlogic.gdx.backends.lwjgl3.NiceLwjgl3Application.<init>(NiceLwjgl3Application.java:80)
	at com.worldwalkergames.legacy.LegacyDesktop.main(LegacyDesktop.java:151)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at com.wildermods.provider.services.WildermythGameProvider.launch(WildermythGameProvider.java:363)
	... 2 more
```

**Comment by Gamebuster19901** [comment]
Vanilla issue. Vanilla Stacktrace:

```
0:20:628 5 LegacyDesktop exiting due to fatal runtime error java.lang.NullPointerException
	at com.worldwalkergames.legacy.game.campaign.model.GameSettings.getPerilAndOdesEnabled(GameSettings.java:214)
	at com.worldwalkergames.legacy.ui.credits.GameResultsDisplay.buildSummary(GameResultsDisplay.java:569)
	at com.worldwalkergames.legacy.ui.credits.GameResultsDisplay.build(GameResultsDisplay.java:437)
	at com.worldwalkergames.legacy.ui.credits.GameResultsDisplay.before(GameResultsDisplay.java:372)
	at com.worldwalkergames.engine.DrivableContainer.driveChild(DrivableContainer.java:79)
	at com.worldwalkergames.scratchpad.CreditsLab.update(CreditsLab.java:210)
	at com.worldwalkergames.ViewStackManager.update(ViewStackManager.java:99)
	at com.worldwalkergames.scratchpad.ui.ScreenManager.update(ScreenManager.java:41)
	at com.worldwalkergames.engine.DrivableContainer.update(DrivableContainer.java:39)
	at com.worldwalkergames.scratchpad.EmbeddedScratchpadScreen.update(EmbeddedScratchpadScreen.java:143)
	at com.worldwalkergames.engine.DrivableContainer.update(DrivableContainer.java:39)
	at com.worldwalkergames.legacy.ui.LegacyUIRoot.update(LegacyUIRoot.java:662)
	at com.worldwalkergames.legacy.ui.MainScreen.update(MainScreen.java:214)
	at com.worldwalkergames.legacy.LegacyDesktop.render(LegacyDesktop.java:344)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
	at com.badlogic.gdx.backends.lwjgl3.NiceLwjgl3Application.loop(NiceLwjgl3Application.java:104)
	at com.badlogic.gdx.backends.lwjgl3.NiceLwjgl3Application.<init>(NiceLwjgl3Application.java:80)
	at com.worldwalkergames.legacy.LegacyDesktop.main(LegacyDesktop.java:151)
```
