### ISSUE TITLE
Serialization issues when creating mods

### ISSUE THREAD

**Issue by Gamebuster19901** [WilderForge/WilderForge#54]
Happens when saving mods. Looks like a conflict between java module system and wildermyth

```
[main/ERROR] [ClientDataContext] Mods Changed. Active mod list:  [{ModEntry: 'ASM 9.6 (ASM10_EXPERIMENTAL)'}, {ModEntry: 'Fabric Loader'}, {ModEntry: 'OpenJDK 64-Bit Server VM'}, {ModEntry: 'Spongepowered Mixin (Fabric Fork)'}, {ModEntry: 'MixinExtras'}, {ModEntry: 'test2'}, {ModEntry: 'WilderForge'}, {ModEntry: 'Wildermyth'}]
[main/WARN] [DesignIterationSystem] Data has changed, re-importing aspects and effects!
[main/ERROR] [ClientDataContext] Loading item data with DLC Armors and Skins ON
[main/ERROR] [ClientDataContext] Loading item data with DLC Omenroad ON
[main/ERROR] [ClientDataContext] deleted effect: test2_tEST.json
[main/ERROR] [FaultTolerantInputMultiplexer] Unhandled exception in response to user input! com.badlogic.gdx.utils.SerializationException: Serialization trace:
com.badlogic.gdx.utils.reflect.Field@499d1026 (net.fabricmc.loader.impl.metadata.ModOriginImpl)
com.badlogic.gdx.utils.reflect.Field@74213bb4 (net.fabricmc.loader.impl.ModContainerImpl)
com.badlogic.gdx.utils.reflect.Field@18b33243 (com.wildermods.wilderforge.api.modLoadingV1.CoremodInfo)
com.badlogic.gdx.utils.reflect.Field@4c5bcc6e (com.worldwalkergames.legacy.game.campaign.model.GameSettings$ModEntry)
	at com.badlogic.gdx.utils.Json.writeFields(Json.java:335)
	at com.badlogic.gdx.utils.Json.writeValue(Json.java:681)
	at com.badlogic.gdx.utils.Json.writeFields(Json.java:328)
	at com.badlogic.gdx.utils.Json.writeValue(Json.java:681)
	at com.badlogic.gdx.utils.Json.writeFields(Json.java:328)
	at com.badlogic.gdx.utils.Json.writeValue(Json.java:681)
	at com.badlogic.gdx.utils.Json.writeFields(Json.java:328)
	at com.badlogic.gdx.utils.Json.writeValue(Json.java:681)
	at com.badlogic.gdx.utils.Json.toJson(Json.java:279)
	at com.badlogic.gdx.utils.Json.toJson(Json.java:238)
	at com.badlogic.gdx.utils.Json.toJson(Json.java:227)
	at com.worldwalkergames.serialization.Serializer.write(Serializer.java:134)
	at com.worldwalkergames.serialization.Serializer.clone(Serializer.java:153)
	at com.worldwalkergames.legacy.editor.ModConfigPopup.<init>(ModConfigPopup.java:59)
	at com.worldwalkergames.legacy.editor.EditorContextBar.lambda$build$2(EditorContextBar.java:149)
	at com.worldwalkergames.communication.observer.signals.Signal2.dispatch(Signal2.java:188)
	at com.worldwalkergames.ui.NiceButton.tryClick(NiceButton.java:104)
	at com.worldwalkergames.ui.NiceButton$1.clicked(NiceButton.java:64)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:124)
	at com.worldwalkergames.legacy.ui.FaultTolerantInputMultiplexer.touchUp(FaultTolerantInputMultiplexer.java:63)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:378)
	at com.badlogic.gdx.backends.lwjgl3.NiceLwjgl3Application.loop(NiceLwjgl3Application.java:104)
	at com.badlogic.gdx.backends.lwjgl3.NiceLwjgl3Application.<init>(NiceLwjgl3Application.java:80)
	at com.worldwalkergames.legacy.LegacyDesktop.main(LegacyDesktop.java:151)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at com.wildermods.provider.services.WildermythGameProvider.launch(WildermythGameProvider.java:364)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final sun.nio.fs.UnixFileSystem sun.nio.fs.UnixPath.fs accessible: module java.base does not "opens sun.nio.fs" to unnamed module @7205765b
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.badlogic.gdx.utils.reflect.Field.setAccessible(Field.java:54)
	at com.badlogic.gdx.utils.Json.getFields(Json.java:213)
	at com.badlogic.gdx.utils.Json.writeFields(Json.java:304)
	at com.badlogic.gdx.utils.Json.writeValue(Json.java:681)
	at com.badlogic.gdx.utils.Json.writeValue(Json.java:549)
	at com.badlogic.gdx.utils.Json.writeFields(Json.java:328)
	... 35 more
```

**Comment by Gamebuster19901** [comment]
Fixed in 4c5e421
