### ISSUE TITLE
Deadlock in EventBus

### ISSUE THREAD

**Issue by Gamebuster19901** [WilderForge/WilderForge#88]
```
2024-12-07 21:41:44
Full thread dump OpenJDK 64-Bit Server VM (17.0.13+11-Ubuntu-2ubuntu122.04 mixed mode, sharing):

Threads class SMR info:
_java_thread_list=0x000075aa048ced10, length=17, elements={
0x000075ab5801cd60, 0x000075ab58173720, 0x000075ab58174b10, 0x000075ab5817b1b0,
0x000075ab5817c570, 0x000075ab5817d990, 0x000075ab5817f3d0, 0x000075ab58180910,
0x000075ab58181d90, 0x000075ab5818a9e0, 0x000075ab5818df60, 0x000075ab5894b2d0,
0x000075aab0000ea0, 0x000075a9b01fe3d0, 0x000075aa08005e80, 0x000075aa1c19a650,
0x000075aa1cae3e30
}
_to_delete_list=0x000075aa9809b010, length=18, elements={
0x000075ab5801cd60, 0x000075ab58173720, 0x000075ab58174b10, 0x000075ab5817b1b0,
0x000075ab5817c570, 0x000075ab5817d990, 0x000075ab5817f3d0, 0x000075ab58180910,
0x000075ab58181d90, 0x000075ab5818a9e0, 0x000075ab5818df60, 0x000075ab5894b2d0,
0x000075aab0000ea0, 0x000075a9b01fe3d0, 0x000075aa08005e80, 0x000075aa1c19a650,
0x000075aa1cae3e30, 0x000075aa9809cc70
}

"main" #1 prio=5 os_prio=0 cpu=5631.23ms elapsed=79.85s tid=0x000075ab5801cd60 nid=0x2739d9 waiting on condition  [0x000075ab5e3fc000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.13/Native Method)
        - parking to wait for  <0x000000060ecdf5f8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(java.base@17.0.13/LockSupport.java:211)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.13/AbstractQueuedSynchronizer.java:715)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.13/AbstractQueuedSynchronizer.java:938)
        at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(java.base@17.0.13/ReentrantReadWriteLock.java:959)
        at com.wildermods.wilderforge.api.eventV1.bus.EventBus.register(EventBus.java:75)
        at com.wildermods.autosplitter.Main.onPreInitialization(Main.java:43)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.13/Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.13/NativeMethodAccessorImpl.java:77)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.13/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@17.0.13/Method.java:569)
        at com.wildermods.wilderforge.api.eventV1.bus.EventBus$StaticEventListener.fire(EventBus.java:297)
        at com.wildermods.wilderforge.api.eventV1.bus.EventBus.fire(EventBus.java:148)
        at com.wildermods.wilderforge.launch.WilderForge.init(WilderForge.java:136)
        at com.worldwalkergames.legacy.ui.LegacyUIRoot.handler$zze000$wilderforge$before(LegacyUIRoot.java:1229)
        at com.worldwalkergames.legacy.ui.LegacyUIRoot.before(LegacyUIRoot.java:318)
        at com.worldwalkergames.legacy.ui.MainScreen.before(MainScreen.java:63)
        at com.worldwalkergames.legacy.LegacyDesktop.create(LegacyDesktop.java:318)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:416)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:366)
        at com.badlogic.gdx.backends.lwjgl3.NiceLwjgl3Application.loop(NiceLwjgl3Application.java:104)
        - locked <0x000000060d713940> (a com.badlogic.gdx.utils.Array)
        at com.badlogic.gdx.backends.lwjgl3.NiceLwjgl3Application.<init>(NiceLwjgl3Application.java:80)
        at com.worldwalkergames.legacy.LegacyDesktop.main(LegacyDesktop.java:151)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.13/Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.13/NativeMethodAccessorImpl.java:77)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.13/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@17.0.13/Method.java:569)
        at com.wildermods.provider.WildermythGameProvider.launch(WildermythGameProvider.java:390)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

   Locked ownable synchronizers:
        - None

"Reference Handler" #2 daemon prio=10 os_prio=0 cpu=2.69ms elapsed=79.84s tid=0x000075ab58173720 nid=0x2739e0 waiting on condition  [0x000075ab27af9000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.ref.Reference.waitForReferencePendingList(java.base@17.0.13/Native Method)
        at java.lang.ref.Reference.processPendingReferences(java.base@17.0.13/Reference.java:253)
        at java.lang.ref.Reference$ReferenceHandler.run(java.base@17.0.13/Reference.java:215)

   Locked ownable synchronizers:
        - None

"Finalizer" #3 daemon prio=8 os_prio=0 cpu=0.27ms elapsed=79.84s tid=0x000075ab58174b10 nid=0x2739e1 in Object.wait()  [0x000075ab279f9000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@17.0.13/Native Method)
        - waiting on <0x000000060c28b038> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@17.0.13/ReferenceQueue.java:155)
        - locked <0x000000060c28b038> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@17.0.13/ReferenceQueue.java:176)
        at java.lang.ref.Finalizer$FinalizerThread.run(java.base@17.0.13/Finalizer.java:172)

   Locked ownable synchronizers:
        - None

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 cpu=0.22ms elapsed=79.83s tid=0x000075ab5817b1b0 nid=0x2739e2 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Service Thread" #5 daemon prio=9 os_prio=0 cpu=0.84ms elapsed=79.83s tid=0x000075ab5817c570 nid=0x2739e3 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Monitor Deflation Thread" #6 daemon prio=9 os_prio=0 cpu=2.91ms elapsed=79.83s tid=0x000075ab5817d990 nid=0x2739e4 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"C2 CompilerThread0" #7 daemon prio=9 os_prio=0 cpu=4781.37ms elapsed=79.83s tid=0x000075ab5817f3d0 nid=0x2739e5 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

   Locked ownable synchronizers:
        - None

"C1 CompilerThread0" #15 daemon prio=9 os_prio=0 cpu=811.41ms elapsed=79.83s tid=0x000075ab58180910 nid=0x2739e6 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

   Locked ownable synchronizers:
        - None

"Sweeper thread" #19 daemon prio=9 os_prio=0 cpu=172.52ms elapsed=79.83s tid=0x000075ab58181d90 nid=0x2739e7 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Notification Thread" #20 daemon prio=9 os_prio=0 cpu=0.06ms elapsed=79.83s tid=0x000075ab5818a9e0 nid=0x2739e8 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Common-Cleaner" #21 daemon prio=8 os_prio=0 cpu=1.63ms elapsed=79.83s tid=0x000075ab5818df60 nid=0x2739ea in Object.wait()  [0x000075ab269fd000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@17.0.13/Native Method)
        - waiting on <0x000000060c298f58> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@17.0.13/ReferenceQueue.java:155)
        - locked <0x000000060c298f58> (a java.lang.ref.ReferenceQueue$Lock)
        at jdk.internal.ref.CleanerImpl.run(java.base@17.0.13/CleanerImpl.java:140)
        at java.lang.Thread.run(java.base@17.0.13/Thread.java:840)
        at jdk.internal.misc.InnocuousThread.run(java.base@17.0.13/InnocuousThread.java:162)

   Locked ownable synchronizers:
        - None

"Decompiler thread" #29 daemon prio=1 os_prio=0 cpu=160.52ms elapsed=79.45s tid=0x000075ab5894b2d0 nid=0x273a06 waiting on condition  [0x000075ab256f2000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.13/Native Method)
        - parking to wait for  <0x000000060c811638> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(java.base@17.0.13/LockSupport.java:341)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(java.base@17.0.13/AbstractQueuedSynchronizer.java:506)
        at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.13/ForkJoinPool.java:3465)
        at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.13/ForkJoinPool.java:3436)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@17.0.13/AbstractQueuedSynchronizer.java:1630)
        at java.util.concurrent.LinkedBlockingQueue.take(java.base@17.0.13/LinkedBlockingQueue.java:435)
        at org.spongepowered.asm.mixin.transformer.debug.RuntimeDecompilerAsync.run(RuntimeDecompilerAsync.java:66)
        at java.lang.Thread.run(java.base@17.0.13/Thread.java:840)

   Locked ownable synchronizers:
        - None

"Attach Listener" #60 daemon prio=9 os_prio=0 cpu=59.01ms elapsed=6.95s tid=0x000075aab0000ea0 nid=0x273b9a waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"RMI TCP Accept-0" #61 daemon prio=9 os_prio=0 cpu=1.30ms elapsed=6.70s tid=0x000075a9b01fe3d0 nid=0x273ba0 runnable  [0x000075ab258f2000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.Net.accept(java.base@17.0.13/Native Method)
        at sun.nio.ch.NioSocketImpl.accept(java.base@17.0.13/NioSocketImpl.java:760)
        at java.net.ServerSocket.implAccept(java.base@17.0.13/ServerSocket.java:675)
        at java.net.ServerSocket.platformImplAccept(java.base@17.0.13/ServerSocket.java:641)
        at java.net.ServerSocket.implAccept(java.base@17.0.13/ServerSocket.java:617)
        at java.net.ServerSocket.implAccept(java.base@17.0.13/ServerSocket.java:574)
        at java.net.ServerSocket.accept(java.base@17.0.13/ServerSocket.java:532)
        at sun.management.jmxremote.LocalRMIServerSocketFactory$1.accept(jdk.management.agent@17.0.13/LocalRMIServerSocketFactory.java:52)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(java.rmi@17.0.13/TCPTransport.java:413)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(java.rmi@17.0.13/TCPTransport.java:377)
        at java.lang.Thread.run(java.base@17.0.13/Thread.java:840)

   Locked ownable synchronizers:
        - <0x000000062acf56b0> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)

"RMI TCP Connection(1)-192.168.1.15" #62 daemon prio=9 os_prio=0 cpu=62.42ms elapsed=6.68s tid=0x000075aa08005e80 nid=0x273ba3 runnable  [0x000075ab257f1000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.Net.poll(java.base@17.0.13/Native Method)
        at sun.nio.ch.NioSocketImpl.park(java.base@17.0.13/NioSocketImpl.java:186)
        at sun.nio.ch.NioSocketImpl.timedRead(java.base@17.0.13/NioSocketImpl.java:290)
        at sun.nio.ch.NioSocketImpl.implRead(java.base@17.0.13/NioSocketImpl.java:314)
        at sun.nio.ch.NioSocketImpl.read(java.base@17.0.13/NioSocketImpl.java:355)
        at sun.nio.ch.NioSocketImpl$1.read(java.base@17.0.13/NioSocketImpl.java:808)
        at java.net.Socket$SocketInputStream.read(java.base@17.0.13/Socket.java:966)
        at java.io.BufferedInputStream.fill(java.base@17.0.13/BufferedInputStream.java:244)
        at java.io.BufferedInputStream.read(java.base@17.0.13/BufferedInputStream.java:263)
        - locked <0x000000062a805180> (a java.io.BufferedInputStream)
        at java.io.FilterInputStream.read(java.base@17.0.13/FilterInputStream.java:82)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(java.rmi@17.0.13/TCPTransport.java:569)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(java.rmi@17.0.13/TCPTransport.java:828)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(java.rmi@17.0.13/TCPTransport.java:705)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$545/0x000075aad04f7410.run(java.rmi@17.0.13/Unknown Source)
        at java.security.AccessController.executePrivileged(java.base@17.0.13/AccessController.java:776)
        at java.security.AccessController.doPrivileged(java.base@17.0.13/AccessController.java:399)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(java.rmi@17.0.13/TCPTransport.java:704)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.13/ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.13/ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(java.base@17.0.13/Thread.java:840)

   Locked ownable synchronizers:
        - <0x000000062ae003b0> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
        - <0x000000062ae01238> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"RMI Scheduler(0)" #63 daemon prio=9 os_prio=0 cpu=0.12ms elapsed=6.67s tid=0x000075aa1c19a650 nid=0x273ba4 waiting on condition  [0x000075ab266fd000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.13/Native Method)
        - parking to wait for  <0x000000062ace8000> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@17.0.13/LockSupport.java:252)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@17.0.13/AbstractQueuedSynchronizer.java:1679)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@17.0.13/ScheduledThreadPoolExecutor.java:1182)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@17.0.13/ScheduledThreadPoolExecutor.java:899)
        at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@17.0.13/ThreadPoolExecutor.java:1062)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.13/ThreadPoolExecutor.java:1122)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.13/ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(java.base@17.0.13/Thread.java:840)

   Locked ownable synchronizers:
        - None

"JMX server connection timeout 64" #64 daemon prio=9 os_prio=0 cpu=2.30ms elapsed=6.66s tid=0x000075aa1cae3e30 nid=0x273ba6 in Object.wait()  [0x000075ab254f2000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@17.0.13/Native Method)
        - waiting on <0x000000062a8508f8> (a [I)
        at com.sun.jmx.remote.internal.ServerCommunicatorAdmin$Timeout.run(java.management@17.0.13/ServerCommunicatorAdmin.java:171)
        - locked <0x000000062a8508f8> (a [I)
        at java.lang.Thread.run(java.base@17.0.13/Thread.java:840)

   Locked ownable synchronizers:
        - None

"GC Thread#17" os_prio=0 cpu=28.69ms elapsed=77.86s tid=0x000075aac4018260 nid=0x273a24 runnable  

"GC Thread#16" os_prio=0 cpu=20.58ms elapsed=78.18s tid=0x000075aac4018620 nid=0x273a1e runnable  

"GC Thread#15" os_prio=0 cpu=22.98ms elapsed=78.48s tid=0x000075aac4019c60 nid=0x273a18 runnable  

"GC Thread#14" os_prio=0 cpu=43.53ms elapsed=78.48s tid=0x000075aac4019320 nid=0x273a17 runnable  

"GC Thread#13" os_prio=0 cpu=29.83ms elapsed=78.48s tid=0x000075aac4011df0 nid=0x273a16 runnable  

"GC Thread#12" os_prio=0 cpu=35.40ms elapsed=78.48s tid=0x000075aac4011670 nid=0x273a15 runnable  

"G1 Conc#4" os_prio=0 cpu=19.78ms elapsed=78.85s tid=0x000075ab20002dc0 nid=0x273a0f runnable  

"G1 Conc#3" os_prio=0 cpu=20.14ms elapsed=78.85s tid=0x000075ab20002340 nid=0x273a0e runnable  

"G1 Conc#2" os_prio=0 cpu=21.99ms elapsed=78.85s tid=0x000075ab200018f0 nid=0x273a0d runnable  

"G1 Conc#1" os_prio=0 cpu=18.69ms elapsed=78.85s tid=0x000075ab20000ea0 nid=0x273a0c runnable  

"GC Thread#11" os_prio=0 cpu=46.97ms elapsed=79.58s tid=0x000075aac400ed70 nid=0x2739fc runnable  

"GC Thread#10" os_prio=0 cpu=28.98ms elapsed=79.58s tid=0x000075aac400e2f0 nid=0x2739fb runnable  

"GC Thread#9" os_prio=0 cpu=38.76ms elapsed=79.58s tid=0x000075aac400d870 nid=0x2739fa runnable  

"GC Thread#8" os_prio=0 cpu=32.58ms elapsed=79.58s tid=0x000075aac400ca00 nid=0x2739f9 runnable  

"GC Thread#7" os_prio=0 cpu=39.08ms elapsed=79.58s tid=0x000075aac400bbd0 nid=0x2739f8 runnable  

"GC Thread#6" os_prio=0 cpu=37.24ms elapsed=79.58s tid=0x000075aac400b190 nid=0x2739f7 runnable  

"GC Thread#5" os_prio=0 cpu=39.88ms elapsed=79.58s tid=0x000075aac400a750 nid=0x2739f6 runnable  

"GC Thread#4" os_prio=0 cpu=32.86ms elapsed=79.58s tid=0x000075aac4009d40 nid=0x2739f5 runnable  

"GC Thread#3" os_prio=0 cpu=34.95ms elapsed=79.58s tid=0x000075aac4009330 nid=0x2739f4 runnable  

"GC Thread#2" os_prio=0 cpu=33.46ms elapsed=79.58s tid=0x000075aac4008920 nid=0x2739f3 runnable  

"GC Thread#1" os_prio=0 cpu=38.83ms elapsed=79.58s tid=0x000075aac4007f10 nid=0x2739f2 runnable  

"VM Periodic Task Thread" os_prio=0 cpu=13.67ms elapsed=79.83s tid=0x000075ab5818c330 nid=0x2739e9 waiting on condition  

"VM Thread" os_prio=0 cpu=55.99ms elapsed=79.84s tid=0x000075ab5816f790 nid=0x2739df runnable  

"G1 Service" os_prio=0 cpu=30.56ms elapsed=79.85s tid=0x000075ab5813fce0 nid=0x2739de runnable  

"G1 Refine#0" os_prio=0 cpu=0.06ms elapsed=79.85s tid=0x000075ab5813ede0 nid=0x2739dd runnable  

"G1 Conc#0" os_prio=0 cpu=19.54ms elapsed=79.85s tid=0x000075ab5805f310 nid=0x2739dc runnable  

"G1 Main Marker" os_prio=0 cpu=1.36ms elapsed=79.85s tid=0x000075ab5805e390 nid=0x2739db runnable  

"GC Thread#0" os_prio=0 cpu=31.16ms elapsed=79.85s tid=0x000075ab5804d3b0 nid=0x2739da runnable  

JNI global refs: 51, weak refs: 0

```

**Comment by Gamebuster19901** [comment]
Fixed in e0ecd0f7e1ec42d21e0f143171bca1932d4e422d
